import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Vercel test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
        <div className={`${styles.description} ${styles.centerText}`}>
  <h1 className={`${styles.centerHorizontally} ${styles.largeText}`}>Hello, world!</h1>
</div>


        </div>
      </main>
    </>
  );
}